# Generated by Django 6.0.3 on 2026-04-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='name',
        ),
    ]
